fix: smoke test

diff --git a/.circleci/ansible/smoke-test.yml b/.circleci/ansible/smoke-test.yml
--- a/.circleci/ansible/smoke-test.yml
+++ b/.circleci/ansible/smoke-test.yml
@@ -26,10 +26,10 @@
           dig +short myip.opendns.com @resolver1.opendns.com > url.txt
           URL="http://$(cat url.txt):9090"
           if curl "$URL/api/status" | grep "ok"
-            then
-                echo "Backend smoke test succeeded"
-                exit 0
-            else
-                echo "Failed Backend smoke test"
-                exit 1
-            fi
+          then
+              echo "Backend smoke test succeeded"
+              exit 0
+          else
+              echo "Failed Backend smoke test"
+              exit 1
+          fi
