fix: smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -209,17 +209,20 @@ jobs:
           command: |
             export BACKEND_IP=$(aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --filter 'Name=tag:Name,Values="backend-${CIRCLE_WORKFLOW_ID:0:7}"' \
+            --filter 'Name=tag:project,Values=udapeople' \
             --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo $API_URL > url.txt
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
+            arrIN=(${BACKEND_IP// / })
+            export API_URL1="http://${arrIN[0]}:3030"
+            echo $API_URL1 > url1.txt
+            export API_URL2="http://${arrIN[1]}:3030"
+            echo $API_URL2 > url2.txt
+            cat url1.txt
+            cat url2.txt
       - persist_to_workspace:
           root: ./
           paths:
-            - url.txt
+            - url1.txt
+            - url2.txt
 
   node-exporter:
     executor: ansible-exec-env
@@ -359,7 +362,16 @@ jobs:
       - run:
           name: Smoke test backend
           command: |
-            if curl "$(cat url.txt)/api/status" | grep "ok"
+            if curl "$(cat url1.txt)/api/status" | grep "ok"
+            then
+                echo "Backend smoke test succeeded"
+                exit 0
+            else
+                echo "Failed Backend smoke test"
+                exit 1
+            fi
+
+            if curl "$(cat url2.txt)/api/status" | grep "ok"
             then
                 echo "Backend smoke test succeeded"
                 exit 0
